### ISSUE TITLE
Please create branch for 4.1.x (and possibly 4.0.x)

### ISSUE THREAD

**Issue by batliner** [gquintard/libvmod-str#1]
The documentation states that to build this VMOD against varnish cache 4.1 then the VMOD must be built from branch 4.1. There is only a master branch though. Can a branch for 4.1 be created?

If possible could a branch for 4.0 also be created?

**Comment by gquintard** [comment]
I created the 4.1 branch and it should be okay, would you mind testing and re-opening if something fails for you?

4.0 won't be supported as it doesn't have optional arguments.
